dist: xenial

language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - android-28

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7 -y
  - sudo apt-get update
  - sudo apt-get install --force-yes python2.7
  - openssl aes-256-cbc -K $encrypted_e2838fa2ea2b_key -iv $encrypted_e2838fa2ea2b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

before_script:
  - ./scripts/bump --patch

script:
  - ./gradlew assembleRelease

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
  - sudo pip2 install -r scripts/requirements.txt

deploy:
  provider: script
  script: ./scripts/upload --production
  on:
      branch: master

after_deploy:
  - ./scripts/commit-and-push
