language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - android-28

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_e2838fa2ea2b_key -iv $encrypted_e2838fa2ea2b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

before_script:
  - ./scripts/bump --patch

script:
  - ./gradlew assembleRelease
